In [1]:
import sys
import os

os.chdir("..")
print("Working directory:", os.getcwd())

sys.path.append(".")

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

from src.load_data import load_raw
from src.clean_data import run_all

Working directory: C:\Users\Jessica\Desktop\projects\tiktok-analysis-dashboard

In [2]:
df = load_raw("tiktok_data.csv") #read the dataset
print(f"Raw shape: {df.shape}")
df.head()

Loaded raw data (760, 10)
Raw shape: (760, 10)

,id_video,duration_seconds,text_part,hashtags,human_time,author_followers,author_likes,id_sound,views,likes
0,1,13.0,А че такое?,"попугай, жако, попугайжако, говорящийпопугай, ...",2018-08-08 20:58:31,675900.0,7500000.0,7.028884e+18,144600000.0,4400000.0
1,2,9.0,Таксист в шоке😱 Inst: Andrey_Pryahin,NaN,2016-01-29 06:16:13,2300000.0,42600000.0,6.870179e+18,113300000.0,5300000.0
2,3,52.0,NaN,рекомендации,2018-12-30 09:24:42,58400.0,613400.0,7.052607e+18,105100000.0,505300.0
3,4,60.0,"Учитесь хитрить, как она 😄😉",NaN,2021-03-10 19:57:42,523900.0,11200000.0,6.984582e+18,96700000.0,3000000.0
4,5,16.0,телефонный пранк от говорящего ворона Карлушы,"пранк, шутка, говорящийворонкарлуша, воронгово...",2020-03-21 11:59:19,943700.0,16800000.0,7.052249e+18,139200000.0,5900000.0

In [3]:
# drop any rows with missing caption
print("Nulls before cleaning:")
print(df.isnull().sum())

Nulls before cleaning:
id_video              0
duration_seconds      9
text_part           102
hashtags             64
human_time            9
author_followers      9
author_likes         11
id_sound              9
views                 9
likes                 9
dtype: int64

In [4]:
df = run_all(df)

Cleaning complete: (658, 15)

In [5]:
print("Nulls after cleaning:")
print(df.isnull().sum())

Nulls after cleaning:
id_video             0
duration_seconds     0
text_part            0
hashtags            55
human_time           0
author_followers     0
author_likes         2
id_sound             0
views                0
likes                0
engagement_rate      0
post_date            0
post_hour            0
post_month           0
creator_tier         0
dtype: int64

In [6]:
df.dtypes

id_video                     int64
duration_seconds           float64
text_part                   object
hashtags                    object
human_time          datetime64[ns]
author_followers           float64
author_likes               float64
id_sound                   float64
views                      float64
likes                      float64
engagement_rate            float64
post_date                   object
post_hour                    int32
post_month                   int32
creator_tier                object
dtype: object

In [7]:
# new columns were added
df[["engagement_rate", "post_date", "post_hour",
    "post_month", "creator_tier"]].head(10)

    engagement_rate   post_date  post_hour  post_month    creator_tier
0          0.030429  2018-08-08         20           8  high followers
1          0.046778  2016-01-29          6           1  high followers
3          0.031024  2021-03-10         19           3  high followers
4          0.042385  2020-03-21         11           3  high followers
5          0.050894  2018-12-17         19          12  high followers
6          0.045536  2018-12-17         19          12  high followers
7          0.109589  2022-02-20         22           2  high followers
8          0.073727  2020-06-02          2           6   low followers
10         0.029048  2021-03-11          3           3  high followers
11         0.033627  2024-07-05          2           7  high followers

In [8]:
print("Creator tier distribution:")
print(df["creator_tier"].value_counts())
print(f"\nMedian followers: {df['author_followers'].median():,.0f}")

Creator tier distribution:
creator_tier
high followers    351
low followers     307
Name: count, dtype: int64

Median followers: 28,500

In [9]:
print(f"Final shape: {df.shape}")
df.head()

Final shape: (658, 15)

,id_video,duration_seconds,text_part,hashtags,human_time,author_followers,author_likes,id_sound,views,likes,engagement_rate,post_date,post_hour,post_month,creator_tier
0,1,13.0,А че такое?,"попугай, жако, попугайжако, говорящийпопугай, ...",2018-08-08 20:58:31,675900.0,7500000.0,7.028884e+18,144600000.0,4400000.0,0.030429,2018-08-08,20,8,high followers
1,2,9.0,Таксист в шоке😱 Inst: Andrey_Pryahin,NaN,2016-01-29 06:16:13,2300000.0,42600000.0,6.870179e+18,113300000.0,5300000.0,0.046778,2016-01-29,6,1,high followers
3,4,60.0,"Учитесь хитрить, как она 😄😉",NaN,2021-03-10 19:57:42,523900.0,11200000.0,6.984582e+18,96700000.0,3000000.0,0.031024,2021-03-10,19,3,high followers
4,5,16.0,телефонный пранк от говорящего ворона Карлушы,"пранк, шутка, говорящийворонкарлуша, воронгово...",2020-03-21 11:59:19,943700.0,16800000.0,7.052249e+18,139200000.0,5900000.0,0.042385,2020-03-21,11,3,high followers
5,6,21.0,Statement ✍️,"tennis, tennistv, atptour, fritz",2018-12-17 19:36:27,1800000.0,138300000.0,7.458512e+18,35800.0,1822.0,0.050894,2018-12-17,19,12,high followers

In [10]:
# save to processed
df.to_csv("data/processed/tiktok_clean.csv", index=False)
print("Saved to data/processed/tiktok_clean.csv")

Saved to data/processed/tiktok_clean.csv